# Generated by Django 5.1.3 on 2024-11-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
    ]
