# Generated by Django 5.1.3 on 2024-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_admin_user_admin_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
